# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f3585d3c186759654e075de00b45528af998c32432176fae99898b63ef38afc8917cd5ca6ab6adefb91ec79f1bea7285e8f7d2feaf8a7c239c6d406677689b0

test:
  secret_key_base: 3ca5800d3f6fcbc9af59e379fe9ab3612e7c3775214c023b60ccf2e372f70337fb8759f55a997144350b37d60d69eca4fa0f422f8c9fdaa8973b87fd4656750a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
